### ISSUE TITLE
language-c-quote-0.11.3 does not compile with alex 3.1.5

### ISSUE THREAD

**Issue by peti** [mainland/language-c-quote#57]
Citing from http://hydra.cryp.to/build/1392350/log/raw:

~~~~~
Language/C/Parser/Lexer.x:508:38:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘or’ (imported from Prelude), ‘odd’ (imported from Prelude),
      ‘ord#’ (imported from GHC.Exts)

Language/C/Parser/Lexer.x:508:46:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘or’ (imported from Prelude), ‘odd’ (imported from Prelude),
      ‘ord#’ (imported from GHC.Exts)

Language/C/Parser/Lexer.x:512:38:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘or’ (imported from Prelude), ‘odd’ (imported from Prelude),
      ‘ord#’ (imported from GHC.Exts)

Language/C/Parser/Lexer.x:512:46:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘or’ (imported from Prelude), ‘odd’ (imported from Prelude),
      ‘ord#’ (imported from GHC.Exts)
~~~~

**Comment by peti** [comment]
Ping?

**Comment by mainland** [comment]
I'm happy to accept a pull request that fixes the bug.

**Comment by peti** [comment]
Well, I'll remove the broken package from the Nix distribution until someone has time to fix it.

**Comment by snoyberg** [comment]
Same issue just detected with Stackage.

**Comment by snoyberg** [comment]
Pinging @bitonic, the Stackage maintainer for this package

**Comment by Athas** [comment]
I made a pull request ( https://github.com/mainland/language-c-quote/pull/58 ) that fixes this issue.  It is against the master branch, though.  I can recreate it against dev and add something to the changelog if that would be easier for the maintainer.
